# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
  - nightly
notifications:
  email: false
script:
  julia -e 'using Pkg; Pkg.clone("https://github.com/diffusionbayes/DiffusionDefinition.jl"); Pkg.build("DiffusionDefinition")'
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.3
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
